### PR TITLE
Updated COTS_priority column to use GBRMPA 2024-2025 data

### PR DESCRIPTION
**Pull request by eco-ben**
Replaced the older CoCoNet COTS_priority data with updated data from GBRMPA for 2024/25 year.

### CODE REVIEW

**Review by ConnectedSystems — CHANGES_REQUESTED** [review]
Please detail the data used and the source of data in readme.

If the data attribution and license info can't be found in the source data file, let me know.

**Comment by eco-ben** [comment]
> Please detail the data used and the source of data in readme.
> 
> If the data attribution and license info can't be found in the source data file, let me know.

I added some details, but yeah I couldn't see any license information in the data or email from 5/8

**Comment by ConnectedSystems** [comment]
> I added some details, but yeah I couldn't see any license information in the data or email from 5/8

Just had a quick look. It's in the first tab "Creative Commons License": the data is provided under CC BY-NC 4.0, something like:

"CoTS data provided by GBRMPA under CC BY-NC 4.0 (http://creativecommons.org/licenses/by-nc/4.0)"

**Comment by eco-ben** [comment]
> > I added some details, but yeah I couldn't see any license information in the data or email from 5/8
> 
> Just had a quick look. It's in the first tab "Creative Commons License": the data is provided under CC BY-NC 4.0, something like:
> 
> "CoTS data provided by GBRMPA under CC BY-NC 4.0 (http://creativecommons.org/licenses/by-nc/4.0)"

Sorry I don't see where that is, but good to know thank you. I've put that into the README now

**Comment by ConnectedSystems** [comment]
> Sorry I don't see where that is, but good to know thank you. I've put that into the README now

Are you looking in the provided Excel spreadsheet or something else?

**Comment by eco-ben** [comment]
> Are you looking in the provided Excel spreadsheet or something else?

Yes, TargetReefs_202425.csv ? I only see a single sheet in there since it's a csv file. Maybe I am missing an attachment, hopefully i didn't add the wrong data in

**Comment by ConnectedSystems** [comment]
Oh sorry, thought you were adding data from the recent Excel spreadsheet (CSVs are not excel files).

I think safe to assume it's under Creative Commons but I'll double check

**Review by ConnectedSystems — APPROVED** [review]

**Pull request merged**
